### PR TITLE
Player abilities

### LINKED ISSUE #157: Initialize inventory (Fix bug where abilities cause game to crash)

### PR DESCRIPTION
**Pull request by natdrog**
Refactoring for how player abilities work with the unlocked abilities in the inventory. Now only the selected ability can be used.

Closes #157

### CODE REVIEW

File: Sprint0/MenuItems/Inventory/AbilitySelect.cs [hunk 1]
```diff
@@ -11,16 +11,10 @@ public class AbilitySelect
 {
     private ISprite SelectBackground { get; set; }
     private ISprite SelectionCursor { get; set; }
-    
-    private ISprite SelectedAbility { get; set; }
```
Comment (Will-Blanton) [inline Sprint0/MenuItems/Inventory/AbilitySelect.cs:15]: Good job decreasing the number of fields since it increases readability and makes the class more cohesive.
